name: air_home_retaurant
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
#  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_spinkit: "^4.1.2"
  dotted_border: ^2.0.0
  page_view_indicators: ^2.0.0
  flutter_rating_bar: ^4.0.0
  http: ^0.13.3
  snack: ^2.0.0
  bubble: ^1.2.1
  flutter_facebook_auth: "^3.5.0"
  hive: ^2.0.4
  path_provider:
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  google_sign_in: ^5.0.7
  synchronized: ^3.0.0
  image_picker: ^0.8.4+3
  country_code_picker: ^2.0.2
  firebase_storage: ^10.0.6
  givestarreviews: ^1.0.2
  google_maps_flutter:
  flutter_calendar_carousel: ^2.0.3
  table_calendar: ^3.0.3
  fluttertoast: ^8.0.8
  flutter_chat_bubble: ^2.0.0
  emoji_picker: ^0.1.0
  flutter_slidable: ^1.1.0
  country_list_pick: ^1.0.1+5
  flutter_html: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/main_logo.png
    - assets/images/left-arrow.png
    - assets/images/right-chevron.png
    - assets/images/information-button.png
    - assets/images/smartbox.png
    - assets/images/delete.png
    - assets/images/camera.png
    - assets/images/delete-red.png
    - assets/images/logo-splash.png
    - assets/images/minus_round.png
    - assets/images/left-arrow-black.png
    - assets/images/airchef.png
    - assets/images/smile.png
    - assets/images/star.png
    - assets/images/puzzle.png
    - assets/images/plus.png
    - assets/images/plus.png
    - assets/images/air-house.png
    - assets/images/background-pattern.jpg
    - assets/images/dish.png
    - assets/images/destination.png
    - assets/images/bake.png
    - assets/images/chef.png
    - assets/images/icon_send.png
    - assets/images/chat.png
    - assets/images/airguide.png
    - assets/images/back-in-time.png
    - assets/images/translation.png
    - assets/images/group.png
    - assets/images/family.png
    - assets/images/password.png
    - assets/images/no-milk.png

    - assets/images/calendar.png
    - assets/images/calendar-r.png
    - assets/images/apple_icon.png
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png
    - assets/images/menu_icon.png
    - assets/images/shopping_cart.png
    - assets/images/food-tray.png
    - assets/images/chat-b.png
    - assets/images/logout.png
    - assets/images/location-r.png
    - assets/images/search_w.png
    - assets/images/children.png
    - assets/images/edit-r.png
    - assets/images/heart.png
    - assets/images/pinstart.png
    - assets/images/curve-down-arrow.png
    - assets/images/cuisine.png
    - assets/images/Siu.png
    - assets/images/key.png
    - assets/images/icon-phone.png
    - assets/images/icon-google.png
    - assets/images/profile_placeholder.png
    - assets/images/user-image-placeholder.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add cusm fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
